# Generated by Django 3.0.5 on 2020-04-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0003_auto_20200417_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='facility',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='facility',
            field=models.ManyToManyField(to='ticketsystem.Facility'),
        ),
    ]
