# Generated by Django 3.0.5 on 2020-04-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0004_auto_20200417_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='seatcapacity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ticketprice',
            field=models.PositiveIntegerField(),
        ),
    ]
