# Generated by Django 3.0.5 on 2020-04-17 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketsystem', '0005_auto_20200417_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecompany',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
