# Generated by Django 3.0.5 on 2020-04-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0006_vehiclecompany_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclecompany',
            name='password',
        ),
        migrations.RemoveField(
            model_name='vehiclecompany',
            name='username',
        ),
        migrations.AddField(
            model_name='vehiclecompany',
            name='authorizedperson',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
