# Generated by Django 3.0.5 on 2020-04-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0008_auto_20200418_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecompany',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
