# Generated by Django 3.0.5 on 2020-04-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0009_auto_20200419_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclecompany',
            name='email',
        ),
    ]
