# Generated by Django 3.0.5 on 2020-04-19 09:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0010_remove_vehiclecompany_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecompany',
            name='company_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
