# Generated by Django 3.0.5 on 2020-04-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0011_auto_20200419_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='departurefrom',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecompany',
            name='authorizedperson',
            field=models.CharField(max_length=100, null=True, verbose_name='Authorized Person'),
        ),
    ]
