# Generated by Django 3.0.5 on 2020-04-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0012_auto_20200420_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='departureto',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
