# Generated by Django 3.0.5 on 2020-04-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0013_auto_20200420_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='departurefrom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='departureto',
            field=models.IntegerField(null=True),
        ),
    ]
