# Generated by Django 3.0.5 on 2020-04-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0014_auto_20200420_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclecompany',
            old_name='user',
            new_name='user_auth',
        ),
    ]
