# Generated by Django 3.0.5 on 2020-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0016_remove_reservation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='busName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
