# Generated by Django 3.0.5 on 2020-04-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0017_reservation_busname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketsystem.VehicleCompany'),
        ),
    ]
