# Generated by Django 3.0.5 on 2020-04-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0020_auto_20200422_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
