# Generated by Django 3.0.5 on 2020-04-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0021_seatplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatplan',
            name='formatname',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='seatplan',
            name='seatformt',
            field=models.TextField(null=True),
        ),
    ]
