# Generated by Django 3.0.5 on 2020-04-22 06:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0022_auto_20200422_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatplan',
            name='seatformt',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
