# Generated by Django 3.0.5 on 2020-04-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0024_auto_20200422_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='seatplan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
