# Generated by Django 3.0.5 on 2020-04-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0025_auto_20200422_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='seatplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketsystem.SeatPlan'),
        ),
    ]
