# Generated by Django 3.0.5 on 2020-04-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0026_auto_20200422_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='totalprice',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
