# Generated by Django 3.0.5 on 2020-04-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0027_auto_20200424_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seatnumber',
            field=models.CharField(max_length=200),
        ),
    ]
