# Generated by Django 3.0.5 on 2020-04-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0028_auto_20200425_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatplan',
            name='seatlayoutimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehiclecompany',
            name='companylogo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
