# Generated by Django 3.0.5 on 2020-04-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0029_auto_20200430_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatplan',
            name='seatlayoutimage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Seat Layout'),
        ),
        migrations.AlterField(
            model_name='vehiclecompany',
            name='companylogo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Company Logo'),
        ),
    ]
