# Generated by Django 3.0.5 on 2020-05-01 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0030_auto_20200430_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seatplan',
            options={'ordering': ('formatname',)},
        ),
    ]
