# Generated by Django 3.0.5 on 2020-05-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0031_auto_20200501_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecompany',
            name='account_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Deactivated', 'Deactivated')], default='Pending', max_length=20),
        ),
    ]
